#! /bin/bash
# activate the grub menu over the serial output

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

set -a

if ! ifclass SERIAL; then
    exit 0
fi

# do not set up grub menu over the serial output during dirinstall
if [ "$FAI_ACTION" = "dirinstall" ] ; then
    exit 0
fi
# during softupdate use this file
[ -r $LOGDIR/disk_var.sh ] && . $LOGDIR/disk_var.sh


# skip the rest, if not an initial installation
if [ $FAI_ACTION != "install" ]; then
    $ROOTCMD update-grub
    exit $error
fi

cat > $target/etc/default/grub <<EOF
# This file has been installed by the script from FAI
# /srv/fai/config/scripts/GRUB_PC/20-serial

# If you change this file, run 'update-grub' afterwards to update
# /boot/grub/grub.cfg.
# For full documentation of the options in this file, see:
#   info -f grub -n 'Simple configuration'

GRUB_DEFAULT=saved
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT='quiet'
GRUB_CMDLINE_LINUX='console=tty0 console=ttyS0,115200n8'

GRUB_TERMINAL=serial
GRUB_SERIAL_COMMAND='serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1'
EOF

$ROOTCMD update-grub
echo UPDATED GRUB for SERIAL output on ttyS0

exit $error
